### ISSUE TITLE
Release v5.0.0

### ISSUE THREAD

**Issue by jelhan** [ember-bootstrap/ember-bootstrap-power-select#347]
This issue tracks breaking changes, which we should consider for next major version.

- [x] Drop support for Node 12 (#351)
- [x] Drop support for Ember < 3.28 (#350)
- [x] Drop support for Ember Bootstrap 4 (#352)
- [x] Drop support for Ember Power Select 4 and 5 (#353)
- [x] Add peer dependencies for ember-bootstrap, ember-power-select and others (#354)
- [ ] ...

**Comment by jelhan** [comment]
@simonihmig Do you have anything additionally, which should be included in the next major?

**Comment by jelhan** [comment]
Released [v5.0.0-0](https://github.com/ember-bootstrap/ember-bootstrap-power-select/releases/tag/v5.0.0-0). Having a RC out of the door will give us some time to double check if we want to include any additional breaking change.

**Comment by simonihmig** [comment]
That looks good to me, nothing to add! Thanks a lot for doing the work here and taking ownership! 🙏

**Comment by jelhan** [comment]
Thanks for your feedback. Just released the v5.0.0-0 as stable version.
